image: alpine/latest
packages:
- e2fsprogs
- qemu-img
- xz
sources:
- https://github.com/oasislinux/build-qemu
artifacts:
- oasis-qemu.tar.xz
environment:
  KERNEL_URL: https://patchouli.sr.ht/builds.sr.ht/artifacts/~mcf/594565/ea8ea562d4f11f42/qemu-bzImage
tasks:
- build: |
    cd build-qemu
    mkdir oasis-qemu
    sudo modprobe nbd
    sudo ./build oasis-qemu/root.qcow2
    cp run README.md oasis-qemu
    curl -Lo oasis-qemu/bzImage $KERNEL_URL
    tar cvfJ ~/oasis-qemu.tar.xz oasis-qemu
